plugins {
    id 'groovy'
    id 'project.camus.library-webflux-conventions'
}

dependencies {
    implementation project(':common')
    implementation project(':common:common-webflux')
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation project(':common:common-test-support')
    testImplementation 'org.wiremock:wiremock-standalone:3.13.2'
}

test {
    useJUnitPlatform()
}
