plugins {
    id 'project.camus.java-conventions'
}

group = 'project.camus'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:3.0.3'
    testImplementation 'io.projectreactor:reactor-test'
}