CREATE TABLE task
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255),
    content          TEXT,
    priority         INTEGER,
    archived         BOOLEAN NOT NULL DEFAULT FALSE,
    version          BIGINT,
    created_at       TIMESTAMP,
    created_by       VARCHAR(255),
    last_modified_at TIMESTAMP,
    last_modified_by VARCHAR(255)
);
