apiVersion: v1
kind: Service
metadata:
  name: task-consumer
  labels:
    app.kubernetes.io/name: task-consumer
spec:
  selector:
    app.kubernetes.io/name: task-consumer
  ports:
    - name: http
      port: 9091
      targetPort: http
