apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pdb.yaml
# 내용이 바뀌면 이름의 hash 가 바뀌어 Deployment 가 다시 배포된다.
configMapGenerator:
  - name: auth-server
    envs:
      - auth-server.env
    options:
      labels:
        app.kubernetes.io/name: auth-server
