apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/part-of: camus
resources:
  - auth-server
  - gateway
  - task-service
  - task-consumer
  - ingress.yaml
