plugins {
    id 'groovy'
    id 'project.camus.library-webmvc-conventions'
}

dependencies {
    implementation project(':common')
    implementation project(':common:common-webmvc')
    implementation platform("software.amazon.awssdk:bom:${awsVersion}")
    implementation 'software.amazon.awssdk:kms'
    implementation 'software.amazon.awssdk:s3'
    implementation 'software.amazon.awssdk:dynamodb'
    implementation 'software.amazon.awssdk:cloudfront'
}

test {
    useJUnitPlatform()
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}